"""empty message

Revision ID: a7f44a124e7f
Revises: f31527281405
Create Date: 2023-12-06 02:27:14.237072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f44a124e7f'
down_revision: Union[str, None] = 'f31527281405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times', sa.Column('checkin_img', sa.String(), nullable=True))
    op.add_column('times', sa.Column('checkout_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'checkout_img')
    op.drop_column('times', 'checkin_img')
    # ### end Alembic commands ###
