"""empty message

Revision ID: b9652e38ef31
Revises: d1334582eaf1
Create Date: 2023-12-04 07:51:35.342890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9652e38ef31'
down_revision: Union[str, None] = 'd1334582eaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'times', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'times', type_='foreignkey')
    # ### end Alembic commands ###
