"""empty message

Revision ID: f31527281405
Revises: b9652e38ef31
Create Date: 2023-12-05 04:35:41.575777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31527281405'
down_revision: Union[str, None] = 'b9652e38ef31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times', sa.Column('checkin_at', sa.DateTime(), nullable=False))
    op.add_column('times', sa.Column('checkout_at', sa.DateTime(), nullable=True))
    op.add_column('times', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'completed')
    op.drop_column('times', 'checkout_at')
    op.drop_column('times', 'checkin_at')
    # ### end Alembic commands ###
