"""empty message

Revision ID: dc0288bfc904
Revises: 2e65c8df4fd2
Create Date: 2023-11-14 15:22:14.664118

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc0288bfc904"
down_revision: Union[str, None] = "2e65c8df4fd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cameras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("faces", sa.Column("person_id", sa.UUID(), nullable=True))
    op.add_column("faces", sa.Column("camera_id", sa.UUID(), nullable=True))
    op.drop_constraint("faces_user_id_fkey", "faces", type_="foreignkey")
    op.create_foreign_key(None, "faces", "cameras", ["camera_id"], ["id"])
    op.create_foreign_key(None, "faces", "persons", ["person_id"], ["id"])
    op.drop_column("faces", "confidence")
    op.drop_column("faces", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faces", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column(
        "faces",
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "faces", type_="foreignkey")
    op.drop_constraint(None, "faces", type_="foreignkey")
    op.create_foreign_key("faces_user_id_fkey", "faces", "persons", ["user_id"], ["id"])
    op.drop_column("faces", "camera_id")
    op.drop_column("faces", "person_id")
    op.drop_table("cameras")
    # ### end Alembic commands ###
