"""empty message

Revision ID: 26e9d5629a1a
Revises: 3191c7aa3651
Create Date: 2023-11-13 16:38:35.807012

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26e9d5629a1a"
down_revision: Union[str, None] = "3191c7aa3651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("faces", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("faces", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
