"""empty message

Revision ID: 2871e13e3872
Revises: dc0288bfc904
Create Date: 2023-11-16 10:40:35.461280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2871e13e3872'
down_revision: Union[str, None] = 'dc0288bfc904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('h', sa.Integer(), nullable=False))
    op.add_column('faces', sa.Column('drew_image_url', sa.String(length=255), nullable=False))
    op.drop_column('faces', 'drawed_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('drawed_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('faces', 'drew_image_url')
    op.drop_column('faces', 'h')
    # ### end Alembic commands ###
