FROM python:3.11-slim-buster

WORKDIR /app

COPY . .
RUN pip install -r requirements.txt


RUN ["alembic", "upgrade", "head"]

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
