FROM python:3.11-slim-buster

WORKDIR /app

# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y

COPY requirements.txt .
COPY .env
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "__main__.py"]